# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 04:59
from __future__ import unicode_literals

from django.db import migrations
import djangoyearlessdate.models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0007_auto_20190713_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='day',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='month',
        ),
        migrations.AddField(
            model_name='birthday',
            name='date_of_birth',
            field=djangoyearlessdate.models.YearlessDateField(max_length=4, null=True),
        ),
    ]
