# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190703_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avator',
        ),
    ]
